on:
  workflow_dispatch:
    inputs:
      url:
        description: "download url"
        required: true
        type: string
jobs:
  my_job:
    runs-on: ubuntu-22.04
    outputs:
      my_output: ${{ steps.step1.outputs.test}}
    steps:
      - uses: actions/setup-python@v4
      - run: cd .idea
