on:
  workflow_dispatch:
    inputs:
      url:
        description: "download url"
        required: true
        type: string
permissions: write-all
jobs:
  my_job:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/setup-python@v4
      - run: pip install UnityPy
      - uses: actions/checkout@v3
      - run: |
          filename=`wget -nv --content-disposition "${{ inputs.url }}" | grep -o "com.PigeonGames.Phigros\-[0-9]*"`
          python gameInformation.py $filename.apk
          python resource.py $filename.apk
          rm $filename.apk
          echo ${filename:24} > version.txt
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "update resource"
          git push
