on:
  workflow_dispatch:
    inputs:
      url:
        description: "download url"
        required: true
        type: string
permissions: write-all
jobs:
  my_job:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/setup-python@v4
      - run: pip install UnityPy
      - uses: actions/checkout@v3
      - run: |
          wget -nv -O Phigros.apk "${{ inputs.url }}"
          python resource.py Phigros.apk
          rm Phigros.apk
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "update resource"
          git push
