on:
  workflow_dispatch:
    inputs:
      url:
        description: "download url"
        required: true
        type: string
jobs:
  my_job:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "update resource"
          git push
